// Member nation profiles — keyed by TopoJSON country name (world-atlas countries-110m)
// Used by WorldMap (click to open profile) and /nation/:slug
export const MEMBER_NATIONS = {
  "Nigeria":        { slug: "nigeria",        iso: "ng", region: "Africa",                    capital: "Abuja",       chapters: 2, fellows: 48, focus: ["Sovereign Economy","Technology & Sovereignty","Youth & Future"] },
  "Kenya":          { slug: "kenya",          iso: "ke", region: "Africa",                    capital: "Nairobi",     chapters: 2, fellows: 36, focus: ["Climate & Energy","Infrastructure","Health & Longevity"] },
  "Egypt":          { slug: "egypt",          iso: "eg", region: "MENA",                      capital: "Cairo",       chapters: 1, fellows: 32, focus: ["Trade & Capital","Culture & Soft Power"] },
  "South Africa":   { slug: "south-africa",   iso: "za", region: "Africa",                    capital: "Pretoria",    chapters: 2, fellows: 41, focus: ["Climate & Energy","Governance & Rule of Law"] },
  "Ghana":          { slug: "ghana",          iso: "gh", region: "Africa",                    capital: "Accra",       chapters: 1, fellows: 22, focus: ["Education & Talent","Sovereign Economy"] },
  "Ethiopia":       { slug: "ethiopia",       iso: "et", region: "Africa",                    capital: "Addis Ababa", chapters: 1, fellows: 18, focus: ["Infrastructure","Peace & Security"] },
  "Morocco":        { slug: "morocco",        iso: "ma", region: "Africa",                    capital: "Rabat",       chapters: 1, fellows: 25, focus: ["Climate & Energy","Culture & Soft Power"] },
  "Rwanda":         { slug: "rwanda",         iso: "rw", region: "Africa",                    capital: "Kigali",      chapters: 1, fellows: 14, focus: ["Technology & Sovereignty","Health & Longevity"] },
  "Senegal":        { slug: "senegal",        iso: "sn", region: "Africa",                    capital: "Dakar",       chapters: 1, fellows: 16, focus: ["Culture & Soft Power","Education & Talent"] },
  "Tanzania":       { slug: "tanzania",       iso: "tz", region: "Africa",                    capital: "Dodoma",      chapters: 1, fellows: 12, focus: ["Climate & Energy","Infrastructure"] },
  "India":          { slug: "india",          iso: "in", region: "South Asia",                capital: "New Delhi",   chapters: 3, fellows: 86, focus: ["Technology & Sovereignty","Science & Research","Trade & Capital"] },
  "Bangladesh":     { slug: "bangladesh",     iso: "bd", region: "South Asia",                capital: "Dhaka",       chapters: 1, fellows: 21, focus: ["Climate & Energy","Youth & Future"] },
  "Sri Lanka":      { slug: "sri-lanka",      iso: "lk", region: "South Asia",                capital: "Colombo",     chapters: 1, fellows: 14, focus: ["Governance & Rule of Law","Trade & Capital"] },
  "Nepal":          { slug: "nepal",          iso: "np", region: "South Asia",                capital: "Kathmandu",   chapters: 1, fellows: 10, focus: ["Climate & Energy","Youth & Future"] },
  "Bhutan":         { slug: "bhutan",         iso: "bt", region: "South Asia",                capital: "Thimphu",     chapters: 1, fellows: 6,  focus: ["Climate & Energy","Culture & Soft Power"] },
  "Indonesia":      { slug: "indonesia",      iso: "id", region: "Southeast Asia",            capital: "Jakarta",     chapters: 2, fellows: 54, focus: ["Trade & Capital","Infrastructure"] },
  "Vietnam":        { slug: "vietnam",        iso: "vn", region: "Southeast Asia",            capital: "Hanoi",       chapters: 1, fellows: 29, focus: ["Technology & Sovereignty","Trade & Capital"] },
  "Philippines":    { slug: "philippines",    iso: "ph", region: "Southeast Asia",            capital: "Manila",      chapters: 1, fellows: 24, focus: ["Climate & Energy","Youth & Future"] },
  "Thailand":       { slug: "thailand",       iso: "th", region: "Southeast Asia",            capital: "Bangkok",     chapters: 1, fellows: 23, focus: ["Culture & Soft Power","Trade & Capital"] },
  "Malaysia":       { slug: "malaysia",       iso: "my", region: "Southeast Asia",            capital: "Kuala Lumpur",chapters: 1, fellows: 19, focus: ["Technology & Sovereignty","Trade & Capital"] },
  "Singapore":      { slug: "singapore",      iso: "sg", region: "Southeast Asia",            capital: "Singapore",   chapters: 1, fellows: 28, focus: ["Technology & Sovereignty","Trade & Capital"] },
  "Cambodia":       { slug: "cambodia",       iso: "kh", region: "Southeast Asia",            capital: "Phnom Penh",  chapters: 1, fellows: 9,  focus: ["Governance & Rule of Law"] },
  "United Arab Emirates": { slug: "uae",      iso: "ae", region: "MENA",                      capital: "Abu Dhabi",   chapters: 1, fellows: 33, focus: ["Technology & Sovereignty","Trade & Capital"] },
  "Saudi Arabia":   { slug: "saudi-arabia",   iso: "sa", region: "MENA",                      capital: "Riyadh",      chapters: 1, fellows: 31, focus: ["Climate & Energy","Trade & Capital"] },
  "Qatar":          { slug: "qatar",          iso: "qa", region: "MENA",                      capital: "Doha",        chapters: 1, fellows: 17, focus: ["Culture & Soft Power","Trade & Capital"] },
  "Jordan":         { slug: "jordan",         iso: "jo", region: "MENA",                      capital: "Amman",       chapters: 1, fellows: 12, focus: ["Peace & Security","Education & Talent"] },
  "Tunisia":        { slug: "tunisia",        iso: "tn", region: "MENA",                      capital: "Tunis",       chapters: 1, fellows: 10, focus: ["Governance & Rule of Law"] },
  "Oman":           { slug: "oman",           iso: "om", region: "MENA",                      capital: "Muscat",      chapters: 1, fellows: 8,  focus: ["Trade & Capital"] },
  "Bahrain":        { slug: "bahrain",        iso: "bh", region: "MENA",                      capital: "Manama",      chapters: 1, fellows: 7,  focus: ["Trade & Capital"] },
  "Brazil":         { slug: "brazil",         iso: "br", region: "Latin America",             capital: "Brasília",    chapters: 3, fellows: 62, focus: ["Climate & Energy","Culture & Soft Power"] },
  "Mexico":         { slug: "mexico",         iso: "mx", region: "Latin America",             capital: "Mexico City", chapters: 2, fellows: 45, focus: ["Trade & Capital","Infrastructure"] },
  "Argentina":      { slug: "argentina",      iso: "ar", region: "Latin America",             capital: "Buenos Aires",chapters: 1, fellows: 27, focus: ["Science & Research","Culture & Soft Power"] },
  "Colombia":       { slug: "colombia",       iso: "co", region: "Latin America",             capital: "Bogotá",      chapters: 1, fellows: 22, focus: ["Peace & Security","Youth & Future"] },
  "Chile":          { slug: "chile",          iso: "cl", region: "Latin America",             capital: "Santiago",    chapters: 1, fellows: 20, focus: ["Climate & Energy","Science & Research"] },
  "Peru":           { slug: "peru",           iso: "pe", region: "Latin America",             capital: "Lima",        chapters: 1, fellows: 15, focus: ["Climate & Energy","Infrastructure"] },
  "Uruguay":        { slug: "uruguay",        iso: "uy", region: "Latin America",             capital: "Montevideo",  chapters: 1, fellows: 8,  focus: ["Governance & Rule of Law"] },
  "Kazakhstan":     { slug: "kazakhstan",     iso: "kz", region: "Central Asia",              capital: "Astana",      chapters: 1, fellows: 19, focus: ["Trade & Capital","Climate & Energy"] },
  "Uzbekistan":     { slug: "uzbekistan",     iso: "uz", region: "Central Asia",              capital: "Tashkent",    chapters: 1, fellows: 11, focus: ["Trade & Capital","Infrastructure"] },
  "Georgia":        { slug: "georgia",        iso: "ge", region: "Central Asia",              capital: "Tbilisi",     chapters: 1, fellows: 9,  focus: ["Governance & Rule of Law"] },
  "Armenia":        { slug: "armenia",        iso: "am", region: "Central Asia",              capital: "Yerevan",     chapters: 1, fellows: 7,  focus: ["Technology & Sovereignty"] },
  "Azerbaijan":     { slug: "azerbaijan",     iso: "az", region: "Central Asia",              capital: "Baku",        chapters: 1, fellows: 8,  focus: ["Trade & Capital","Climate & Energy"] },
  "Poland":         { slug: "poland",         iso: "pl", region: "Eastern Europe",            capital: "Warsaw",      chapters: 1, fellows: 18, focus: ["Technology & Sovereignty"] },
  "Romania":        { slug: "romania",        iso: "ro", region: "Eastern Europe",            capital: "Bucharest",   chapters: 1, fellows: 12, focus: ["Infrastructure"] },
  "Serbia":         { slug: "serbia",         iso: "rs", region: "Eastern Europe",            capital: "Belgrade",    chapters: 1, fellows: 9,  focus: ["Governance & Rule of Law"] },
  "Moldova":        { slug: "moldova",        iso: "md", region: "Eastern Europe",            capital: "Chișinău",    chapters: 1, fellows: 5,  focus: ["Governance & Rule of Law"] },
  "Fiji":           { slug: "fiji",           iso: "fj", region: "Pacific",                   capital: "Suva",        chapters: 1, fellows: 4,  focus: ["Climate & Energy"] },
  "Papua New Guinea":{ slug: "papua-new-guinea", iso: "pg", region: "Pacific",                capital: "Port Moresby",chapters: 1, fellows: 3,  focus: ["Climate & Energy"] },
  "Samoa":          { slug: "samoa",          iso: "ws", region: "Pacific",                   capital: "Apia",        chapters: 1, fellows: 2,  focus: ["Climate & Energy"] },
  "Malawi":         { slug: "malawi",         iso: "mw", region: "Africa",                    capital: "Lilongwe",    chapters: 1, fellows: 5,  focus: ["Health & Longevity"] },
  "Maldives":       { slug: "maldives",       iso: "mv", region: "South Asia",                capital: "Malé",        chapters: 1, fellows: 3,  focus: ["Climate & Energy"] },
};

// Build a slug-keyed reverse lookup for nation profile pages
export const NATION_BY_SLUG = Object.entries(MEMBER_NATIONS).reduce((acc, [name, data]) => {
  acc[data.slug] = { name, ...data };
  return acc;
}, {});
