name: 🚀 Deploy ICEN Project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |

            cd /var/www/icen-main

            echo "📥 Pull latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "🐳 Rebuilding Docker..."
            docker compose down
            docker compose up -d --build

            echo "✅ Deploy Done"